### ISSUE TITLE
Trying to implement `RaftStorage` trait. Should `Ballot` fields and constructor be private?

### ISSUE THREAD

**Issue by nerdondon** [akiradeveloper/sorock#297]
Hi,

I'm trying to implement the `RaftStorage` trait for an embedded database that I made but am having trouble creating the initial ballot state. The current implementations that are provided either initialize the `Ballot` object directly ([rocksdb](https://github.com/akiradeveloper/lol/blob/master/lol-core/src/storage/rocksdb.rs#L44-L47)) or use the `new` method ([file](https://github.com/akiradeveloper/lol/blob/master/lol-core/src/storage/file.rs#L43) and [memory](https://github.com/akiradeveloper/lol/blob/master/lol-core/src/storage/memory.rs#L16)). The [struct fields](https://github.com/akiradeveloper/lol/blob/bbdb0ec0e3f7b82377f66302900118192dccd3d4/lol-core/src/storage/mod.rs#L22-L23) of ballot have visibility scoped to crate and the [`new` method is completely private](https://github.com/akiradeveloper/lol/blob/bbdb0ec0e3f7b82377f66302900118192dccd3d4/lol-core/src/storage/mod.rs#L26).

If the `Ballot` struct fields are meant to be completely opaque to implementers of the `RaftStorage` trait, can we at least make the `new` method public? Or if I am using `RaftStorage` wrong please let me know that as well.

Thanks!

**Comment by akiradeveloper** [comment]
@nerdondon 

> either initialize the Ballot object directly ([rocksdb](https://github.com/akiradeveloper/lol/blob/master/lol-core/src/storage/rocksdb.rs#L44-L47))

This should use `new` method. I should fix this.

> can we at least make the new method public?

Even if the initializer is public, I suppose you can't implement your own backend in your separate crate because you can't save the ballot (and entry) in your storage. To save the ballot in persistent storage, `BallotB` (B stands for Binary) is defined in `storage::persistency` module to implement conversions to/from `Vec<u8>`. 

I might need to also publish these conversion functions or publish the fields.

**Comment by nerdondon** [comment]
I'd really like to be able to use your project. Are you willing to open up the visibility of the initializer or the struct fields? If you decide it is ok to do one or the other, would you accept that as a contribution or would you like to do that by yourself?

Update:

I don't think it is necessary to make `BallotB` public since you already implement the `Into` and `From` methods. None of the provided implementations directly use those intermediate structs when serializing/deserializing currently. I am in the middle of implementing my own storage backend and was able to use `into` just fine. The only issue, I'm running into is creating the initial `Ballot` state.

**Comment by nerdondon** [comment]
Hi @akiradeveloper, I dont mean to be a bother just wanted to ask if you would be able to have time to take a look or accept a pull request?

**Comment by akiradeveloper** [comment]
> The only issue, I'm running into is creating the initial Ballot state.

OK. You can make a PR to publish `Ballot::new`.

**Comment by nerdondon** [comment]
would it be possible to get this update released by itself (as 0.92) or are there other changes you are waiting to make before doing a release?

**Comment by akiradeveloper** [comment]
Give me some time for maintenance. Then I will release the crate.

**Comment by nerdondon** [comment]
just wanted to say thanks very much for your quick responses and release 🙂
